### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by sajjadsef** [CharlesDias/Yocto-Project-for-iMX6ULL#1]
Following your tutorial on LinkedIn after entering to your docker container, when trying to clone the meta-information by using the repo tool the following error pops up:
```
imx6ull@aa92169034b9:~/oe-core$ repo init -u git://git.toradex.com/toradex-manifest.git -b kirkstone-6.x.y -m tdxref/default.xml
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by CharlesDias** [comment]
@sajjadsef Thanks for report the problem.

I fixed the dockerfile and uploaded the Docker Hub image. Please, try again with the latest Docker image version.
